
export const ALL_PRODUCTS = [
    {
        _id: "",
        modelId: "",
        title:"Bluetooth headphone Apple air pods max",
        description:"Et aliquid aliquid earum voluptatum explicabo veniam. Expedita mollitia inventore distinctio sed. Fugit eos dolores aut ut ut soluta explicabo. Amet doloremque repellat minus quaerat laborum.",
        rating:4.7,
        reviews:[{}],
        price:92.12,
        usdHigh:100,
        color:'',
        tags:['Abc','ccs','1234'],
        stockAmount:10,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Bluetooth20Headphone20Apple20AirPodsMax-300x300.jpg',
        images: [
            'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Bluetooth20Headphone20Apple20AirPodsMax-300x300.jpg',
            'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20iphone201320128GB-300x300.jpg',
            'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20MacBook20Pro201320Touch20Bar20M120256GB202020-300x300.jpg',
            'https://elec.mn/img/products/OpZmXV6we3H7B9aUe0TbWbDxbcLZkauC2Nts2m1b.jpeg',
        ],
        category:{
            value:'Cell Phones'
        },
        sku:{
            value:'iphone-13-pro-max-256gb-28140313'
        },
        memory:{
            unit:"GB",
            size:'128'
        },
        technical:
        [
            {key:"Product Dimensions", value:"8.27 x 4.33 x 0.5 inches"},
            {key:"Item Weight", value:"3.8 ounces"},
            {key:"ASIN", value:"B079HV3tC9"},
            {key:"Item model number", value:"Black&Green Waterproof Phone Pouch"},
            {key:"Special Features", value:"Waterproof, Fit all devices under 7"},
            {key:"Form Factor", value:"Dry Bag"},
            {key:'Manufacturer',value:'X Vision Technology LIMITED'}
            
        ],
        note:
        [
            {key:"Description",type:"html",value:"<p>Et aliquid aliquid earum voluptatum explicabo veniam. Expedita mollitia inventore distinctio sed. Fugit eos dolores aut ut ut soluta explicabo. Amet doloremque repellat minus quaerat laborum</p>"},
            {key:"",value:"https://elec.mn/img/products/OpZmXV6we3H7B9aUe0TbWbDxbcLZkauC2Nts2m1b.jpeg",type:"image"},
            {key:"Description",type:"html",value:"<p>Et aliquid aliquid earum voluptatum explicabo veniam. Expedita mollitia inventore distinctio sed. Fugit eos dolores aut ut ut soluta explicabo. Amet doloremque repellat minus quaerat laborum</p>"},
            {key:"",value:"https://elec.mn/img/products/OpZmXV6we3H7B9aUe0TbWbDxbcLZkauC2Nts2m1b.jpeg",type:"image"}
        ]
    },
    {
        _id: "",
        modelId: "",
        title:"Apple Iphone 13 128GB",
        description:"Omnis soluta illum tenetur et officia sunt placeat. Nisi ut aspernatur hic possimus voluptates illum nulla et. Odit dignissimos voluptatum accusantium sed.",
        rating:4.2,
        price:140,
        usdHigh:140,
        color:'',
        tags:['aac, gef, aaa'],
        stockAmount:0,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20iphone201320128GB-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Apple MacBook Pro 13 Touch Bar M1",
        description:"",
        rating:3.9,
        price:10,
        usdHigh:75.22,
        color:'',
        tags:['Abc, gef, aaa'],
        stockAmount:10,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20MacBook20Pro201320Touch20Bar20M120256GB202020-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Bluetooth Beats Studio Buds",
        description:"",
        rating:4.2,
        price:0.2,
        usdHigh:0.3,
        color:'',
        tags:['Abc, gef, aaa'],
        stockAmount:10,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Bluetooth20Beats20Studio20Buds-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Apple Air Pods2",
        description:"",
        rating:4.45,
        price:1100,
        usdHigh:1200,
        color:'',
        tags:[],
        stockAmount:0,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20Watch20Series2072041mm20GPS2020Sport20Band-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Bluetooth headphone Apple air pods max",
        description:"",
        rating:4.7,
        price:92.12,
        usdHigh:100,
        color:'',
        tags:['Abc, gef, aaa'],
        stockAmount:10,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Bluetooth20Headphone20Apple20AirPodsMax-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Apple Iphone 13 128GB",
        description:"",
        rating:4.2,
        price:140,
        usdHigh:140,
        color:'',
        tags:['aac, gef, aaa'],
        stockAmount:0,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20iphone201320128GB-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Apple MacBook Pro 13 Touch Bar M1",
        description:"",
        rating:3.9,
        price:10,
        usdHigh:75.22,
        color:'',
        tags:['Abc, gef, aaa'],
        stockAmount:10,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20MacBook20Pro201320Touch20Bar20M120256GB202020-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Bluetooth Beats Studio Buds",
        description:"",
        rating:4.2,
        price:0.2,
        usdHigh:0.3,
        color:'',
        tags:['Abc, gef, aaa'],
        stockAmount:10,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Bluetooth20Beats20Studio20Buds-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Apple Air Pods2",
        description:"",
        rating:4.45,
        price:1100,
        usdHigh:1200,
        color:'',
        tags:[],
        stockAmount:0,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20Watch20Series2072041mm20GPS2020Sport20Band-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Bluetooth headphone Apple air pods max",
        description:"",
        rating:4.7,
        price:92.12,
        usdHigh:100,
        color:'',
        tags:['Abc, gef, aaa'],
        stockAmount:10,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Bluetooth20Headphone20Apple20AirPodsMax-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Apple Iphone 13 128GB",
        description:"",
        rating:4.2,
        price:140,
        usdHigh:140,
        color:'',
        tags:['aac, gef, aaa'],
        stockAmount:0,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20iphone201320128GB-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Apple MacBook Pro 13 Touch Bar M1",
        description:"",
        rating:3.9,
        price:10,
        usdHigh:75.22,
        color:'',
        tags:['Abc, gef, aaa'],
        stockAmount:10,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20MacBook20Pro201320Touch20Bar20M120256GB202020-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Bluetooth Beats Studio Buds",
        description:"",
        rating:4.2,
        price:0.2,
        usdHigh:0.3,
        color:'',
        tags:['Abc, gef, aaa'],
        stockAmount:10,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Bluetooth20Beats20Studio20Buds-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Apple Air Pods2",
        description:"",
        rating:4.45,
        price:1100,
        usdHigh:1200,
        color:'',
        tags:[],
        stockAmount:0,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20Watch20Series2072041mm20GPS2020Sport20Band-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Bluetooth headphone Apple air pods max",
        description:"",
        rating:4.7,
        price:92.12,
        usdHigh:100,
        color:'',
        tags:['Abc, gef, aaa'],
        stockAmount:10,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Bluetooth20Headphone20Apple20AirPodsMax-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Apple Iphone 13 128GB",
        description:"",
        rating:4.2,
        price:140,
        usdHigh:140,
        color:'',
        tags:['aac, gef, aaa'],
        stockAmount:0,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20iphone201320128GB-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Apple MacBook Pro 13 Touch Bar M1",
        description:"",
        rating:3.9,
        price:10,
        usdHigh:75.22,
        color:'',
        tags:['Abc, gef, aaa'],
        stockAmount:10,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20MacBook20Pro201320Touch20Bar20M120256GB202020-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Bluetooth Beats Studio Buds",
        description:"",
        rating:4.2,
        price:0.2,
        usdHigh:0.3,
        color:'',
        tags:['Abc, gef, aaa'],
        stockAmount:10,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Bluetooth20Beats20Studio20Buds-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Apple Air Pods2",
        description:"",
        rating:4.45,
        price:1100,
        usdHigh:1200,
        color:'',
        tags:[],
        stockAmount:0,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20Watch20Series2072041mm20GPS2020Sport20Band-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Bluetooth headphone Apple air pods max",
        description:"",
        rating:4.7,
        price:92.12,
        usdHigh:100,
        color:'',
        tags:['Abc, gef, aaa'],
        stockAmount:10,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Bluetooth20Headphone20Apple20AirPodsMax-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Apple Iphone 13 128GB",
        description:"",
        rating:4.2,
        price:140,
        usdHigh:140,
        color:'',
        tags:['aac, gef, aaa'],
        stockAmount:0,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20iphone201320128GB-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Apple MacBook Pro 13 Touch Bar M1",
        description:"",
        rating:3.9,
        price:10,
        usdHigh:75.22,
        color:'',
        tags:['Abc, gef, aaa'],
        stockAmount:10,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20MacBook20Pro201320Touch20Bar20M120256GB202020-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Bluetooth Beats Studio Buds",
        description:"",
        rating:4.2,
        price:0.2,
        usdHigh:0.3,
        color:'',
        tags:['Abc, gef, aaa'],
        stockAmount:10,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Bluetooth20Beats20Studio20Buds-300x300.jpg'
    },
    {
        _id: "",
        modelId: "",
        title:"Apple Air Pods2",
        description:"",
        rating:4.45,
        price:1100,
        usdHigh:1200,
        color:'',
        tags:[],
        stockAmount:0,
        image:'https://demothemedh.b-cdn.net/axtronic/wp-content/uploads/2021/12/Apple20Watch20Series2072041mm20GPS2020Sport20Band-300x300.jpg'
    },
]